-- TODO ADD FILE TO TABLES VIA STAGE INGESTION 
-- TODO ADD SNOWFLAKE QUERY INFORMATIONS
CREATE OR REPLACE VIEW AUDIT.AUDIT_LINEAGE.PURVIEW_LINEAGE_OBJECT_DEPENDENCIES
AS
SELECT
    REFERENCED_DATABASE,
    REFERENCED_SCHEMA,
    REFERENCED_OBJECT_NAME,
    REFERENCED_OBJECT_ID,
    REFERENCED_OBJECT_DOMAIN,
    REFERENCING_DATABASE,
    REFERENCING_SCHEMA,
    REFERENCING_OBJECT_NAME,
    REFERENCING_OBJECT_ID,
    REFERENCING_OBJECT_DOMAIN,
    DEPENDENCY_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
WHERE
    REFERENCED_OBJECT_DOMAIN != 'FUNCTION'
    AND REFERENCING_OBJECT_DOMAIN != 'FUNCTION';
